[project]
name = "auto-merge-development"
version = "0.1.0"
description = ""
authors = [
    { name = "Nilton Teixeira", email = "9078708+niltonfrederico@users.noreply.github.com" },
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["django>=5"]

[tool.poetry]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
